export enum StructureTypeEnum {
  String = 'string',
  Text = 'text',
  SimpleText = 'simpleText',
  File = 'file',
  Image = 'image',
  Video = 'Video',
  Color = 'color',
  List = 'list',
  Url = 'url',
  Select = 'select',
  Object = 'object',
  idSelector = 'idSelector',
  Null = 'null',
}
